import { Link } from 'react-router-dom'
import { whatsappUrl } from '../utils/contact.js'
import './google-ads-detail.css'

const faq = [
  ['Is Google Ads worth it for a small business in Dubai?', 'It can be, when people are already searching for the service you sell. I look at search demand, competition, customer value and acceptable acquisition cost before recommending a budget. The goal is not to buy more clicks. It is to find commercially useful demand.'],
  ['How much should a UAE business spend on Google Ads?', 'There is no useful universal minimum. The right test budget depends on your market, search volume, average customer value and target acquisition cost. I would rather calculate a realistic starting point from your numbers than recommend an arbitrary monthly spend.'],
  ['Why are my Google Ads generating leads but not customers?', 'A lead is not automatically a qualified opportunity. The problem can sit in keyword intent, ad messaging, landing page experience, form qualification, sales follow up or conversion tracking. Where CRM data is available, I look beyond the Google Ads interface to understand lead quality.'],
  ['Can you audit my existing Google Ads account?', 'Yes. I review campaign structure, keywords, search terms, bidding, conversion actions, budget allocation, ad messaging and landing page alignment. The output is a practical priority list rather than a generic audit document.'],
  ['Do you manage Google Ads yourself?', 'Yes. The work is hands on. You deal directly with the person analysing the campaigns and making optimisation decisions rather than passing campaign changes through multiple account layers.'],
  ['Can you fix Google Ads conversion tracking?', 'Yes. I can review whether forms, calls, WhatsApp enquiries and other meaningful actions are being tracked correctly and whether the conversion signals are useful for optimisation.'],
  ['How quickly can Google Ads generate results?', 'Search campaigns can start generating traffic and enquiries soon after launch when relevant demand exists. Reliable optimisation takes enough meaningful data to separate useful patterns from noise. I do not promise an arbitrary result within a fixed number of days.'],
]

const included = [
  ['Account audit', 'Campaign structure, targeting, bidding, settings, keywords and existing conversion actions'],
  ['Keyword strategy', 'Search intent, commercial keywords, match types and negative keyword opportunities'],
  ['Campaign structure', 'Search, Performance Max and local campaigns where they make commercial sense'],
  ['Ad creation', 'Search ad messaging aligned with user intent and the landing page'],
  ['Conversion tracking', 'Forms, calls, WhatsApp actions and other meaningful conversion events'],
  ['Lead quality', 'Distinguishing enquiries from commercially useful leads'],
  ['Budget optimisation', 'Moving budget toward campaigns, keywords and audiences producing stronger signals'],
  ['Search term analysis', 'Removing irrelevant traffic and finding new high intent opportunities'],
  ['Landing page alignment', 'Making the promise in the ad match what users see after clicking'],
  ['Reporting', 'Clear reporting focused on business outcomes rather than vanity metrics'],
]

export default function GoogleAdsDetail() {
  return <main className="google-ads-page" id="main">
    <section className="ga-hero"><div className="ga-hero-grid" aria-hidden="true"/><div className="container ga-hero-inner">
      <Link className="ga-back" to="/services">← Back to services</Link>
      <div className="ga-hero-content">
        <div className="ga-hero-copy"><p className="services-eyebrow">Google Ads Management · Dubai, UAE</p><h1>Google Ads That Turn Search Demand Into <span>Qualified Leads.</span></h1><p className="ga-lead">Your problem is not getting clicks. It is getting the right people to click, enquire and become customers.</p><p className="ga-lead ga-lead-small">I manage Google Ads around search intent, conversion tracking, lead quality and the sales process so your budget is focused on demand that can actually become revenue.</p><a className="ga-primary" href={whatsappUrl} target="_blank" rel="noreferrer">Book a Free 15 Minute Google Ads Audit <span>↗</span></a><p className="ga-trust">No obligation · Dubai based · Hands on management · Conversion tracking · Lead quality</p></div>
        <div className="ga-hero-visual"><div className="ga-visual-ring"/><div className="ga-visual-core"><span>GOOGLE</span><strong>ADS</strong><small>SEARCH → DEMAND → LEADS</small></div><span className="ga-orbit ga-orbit-1">SEARCH INTENT</span><span className="ga-orbit ga-orbit-2">TRACKING</span><span className="ga-orbit ga-orbit-3">LEAD QUALITY</span></div>
      </div>
    </div></section>

    <section className="ga-section"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">The problem</p><h2>Your Google Ads may be generating leads. But are they the right leads?</h2></div><div className="ga-pain-grid">{[['01','“We are getting leads, but most are not serious.”','The campaign may be optimising for form submissions instead of the characteristics of a genuinely valuable prospect.'],['02','“Our cost per lead keeps increasing.”','Budget can drift into keywords and campaigns without understanding which parts of the account are actually producing qualified demand.'],['03','“Google says we are getting conversions, but sales does not agree.”','The advertising platform sees a conversion. Your business needs a customer. Those are not necessarily the same thing.'],['04','“We do not know where the money is going.”','Broad targeting, weak search terms, poor negative keyword management and broken tracking can quietly consume budget.']].map(([n,title,text]) => <article className="ga-pain" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="ga-section-note">The solution is not simply spending more. It is understanding where intent exists, capturing it properly and feeding better conversion signals back into the account.</p></div></section>

    <section className="ga-section ga-included"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">What's included</p><h2>Google Ads management built around qualified demand.</h2><p>This is not campaign setup followed by a monthly report. The work covers the advertising system around your acquisition funnel.</p></div><div className="ga-included-grid">{included.map(([title,text]) => <div className="ga-included-item" key={title}><span>✓</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><div className="ga-outcome"><span>The objective</span><strong>More useful demand from the budget you already have. Not simply more clicks.</strong></div></div></section>

    <section className="ga-section"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">The process</p><h2>How I manage Google Ads for UAE businesses.</h2></div><div className="ga-process">{[['01','Audit','I review the account, campaign structure, keywords, search terms, conversion actions, bidding, budget, ads, landing pages and tracking.'],['02','Identify intent','I separate high intent searches from research traffic, irrelevant searches and low value demand.'],['03','Rebuild and launch','Where necessary, campaigns are restructured around intent, commercial relevance, geography, budget, conversion goals and landing page alignment.'],['04','Optimise','I review search terms, cost per conversion, conversion rates, budget distribution, keyword performance and ad performance, then make evidence based changes.'],['05','Connect marketing to sales','Where CRM data is available, I use downstream lead quality information to understand which acquisition sources produce better opportunities.']].map(([n,title,text]) => <article className="ga-process-item" key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

    <section className="ga-proof"><div className="container"><div className="ga-proof-grid"><div><p className="services-eyebrow">Relevant experience</p><h2>Paid acquisition for businesses where lead quality matters.</h2><p>I have worked across immigration and visa services, attestation and professional services, healthcare and wellness, recruitment and HR, business services, and B2B and high consideration services.</p></div><div className="ga-proof-card"><span>Experience across</span><strong>Immigration · Attestation · Healthcare · Recruitment · B2B</strong><p>Once verified campaign figures are available, this section can be upgraded with specific spend, qualified lead and conversion metrics. I will not publish unsupported numbers.</p></div></div></div></section>

    <section className="ga-section"><div className="container ga-diff"><div><p className="services-eyebrow">Why Ashwin</p><h2>You work directly with the person managing the campaigns.</h2></div><div><p>You do not need another layer between the business and the person making changes inside the advertising account.</p><p>I work across <strong>Google Ads → Landing Page → Tracking → CRM → Lead Quality</strong>. That changes the question from “How many leads did Google generate?” to “Did the marketing system generate the type of demand the business actually wants?”</p></div></div></section>

    <section className="ga-section ga-faq"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">FAQ</p><h2>Questions business owners ask before handing over ad budget.</h2></div><div className="ga-faq-list">{faq.map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>

    <section className="ga-section ga-social"><div className="container"><p className="services-eyebrow">Keep the acquisition system connected</p><h2>Google Ads works better when the rest of the journey is measured.</h2><div className="ga-related-grid"><Link to="/services/landing-page-optimisation"><span>01</span><strong>Landing Page Optimisation</strong><small>Reduce friction after the click →</small></Link><Link to="/services/lead-generation"><span>02</span><strong>Lead Generation</strong><small>Connect traffic to a healthier pipeline →</small></Link><Link to="/services/hubspot"><span>03</span><strong>HubSpot CRM & Automation</strong><small>Track what happens after the lead →</small></Link></div></div></section>

    <section className="ga-final"><div className="container"><p className="services-eyebrow">Not sure where your Google Ads budget is going?</p><h2>Let's spend 15 minutes looking at it.</h2><p>I will review the biggest potential issues in your current setup and explain what I would prioritise.</p><a className="ga-primary" href={whatsappUrl} target="_blank" rel="noreferrer">Book a Free 15 Minute Google Ads Audit <span>↗</span></a><small>No long presentation. No obligation. Just a practical review.</small></div></section>
  </main>
}
