import { Link } from 'react-router-dom'
import { whatsappUrl } from '../utils/contact.js'
import '../pages/google-ads-detail.css'

const faq = [
  ['Is Meta Ads worth it for a small business in Dubai?', 'It can be, when the offer is strong enough to create demand and the audience can be reached with relevant messaging. I look at the offer, audience, customer value, lead economics and testing requirements before recommending a budget.'],
  ['Why are my Meta Ads generating leads but poor quality enquiries?', 'Cheap lead volume can hide weak audience signals, vague offers, weak creative promises or insufficient qualification. I look at the full journey from audience and creative through forms, landing pages and sales quality rather than optimising only for the lowest cost per lead.'],
  ['How much should a UAE business spend on Meta Ads?', 'There is no useful universal minimum. The starting budget depends on audience size, offer economics, expected lead value and how much testing is needed to find a repeatable combination of audience, creative and offer.'],
  ['Do you create the Meta Ads creatives?', 'I provide the strategic creative direction: hooks, angles, offers, messaging, testing hypotheses and creative briefs. Production can work with your existing designer, content team or suitable production support depending on the campaign.'],
  ['Can you improve Meta lead forms and landing pages?', 'Yes. The form or landing page is part of the acquisition system. I review friction, qualification questions, message match and the information needed to turn an enquiry into a useful sales opportunity.'],
  ['How do you test Meta Ads without wasting budget?', 'Testing is structured around a clear hypothesis. Audience, offer and creative variables are separated where practical, early signals are reviewed, weak combinations are reduced and budget is moved toward evidence rather than personal preference.'],
  ['Can you connect Meta Ads to CRM and lead quality?', 'Where CRM data is available, I use downstream lead information to understand which campaigns and sources are producing better opportunities. This helps move optimisation beyond cheap lead volume.'],
]

const included = [
  ['Audience strategy', 'Define the people, signals, pain points and buying situations the campaign should reach.'],
  ['Offer strategy', 'Turn the service into a clear reason for the right prospect to stop, understand and enquire.'],
  ['Creative direction', 'Develop hooks, angles, messaging and testing briefs designed for the feed environment.'],
  ['Campaign structure', 'Separate prospecting, retargeting and lead generation around clear objectives and budget.'],
  ['Lead forms', 'Build qualification questions and friction around the type of enquiry the sales team actually wants.'],
  ['Landing pages', 'Align the post click experience with the ad promise and make the next action clear.'],
  ['Retargeting', 'Re engage relevant visitors and engaged audiences with messaging suited to their stage.'],
  ['Creative performance', 'Review which hooks, formats, messages and offers are producing stronger signals.'],
  ['Lead quality', 'Use available sales or CRM information to distinguish enquiries from useful opportunities.'],
  ['Testing and optimisation', 'Test audiences, offers, creative and campaign structure, then move budget toward stronger evidence.'],
]

export default function MetaAdsService() {
  return <main className="google-ads-page meta-ads-page" id="main">
    <section className="ga-hero"><div className="ga-hero-grid" aria-hidden="true"/><div className="container ga-hero-inner">
      <Link className="ga-back" to="/services">← Back to services</Link>
      <div className="ga-hero-content">
        <div className="ga-hero-copy"><p className="services-eyebrow">Meta Ads Management · Dubai, UAE</p><h1>Meta Ads That Turn <span>Attention Into Qualified Leads.</span></h1><p className="ga-lead ga-lead-small">I build Facebook and Instagram campaigns around audience, offer, creative and lead quality so your advertising creates demand instead of simply generating cheap enquiries.</p><a className="ga-primary" href={whatsappUrl} target="_blank" rel="noreferrer">Book a Free 15 Minute Meta Ads Audit <span>↗</span></a><p className="ga-trust">No obligation · Dubai based · Hands on management · Creative testing · Lead quality</p></div>
        <div className="ga-hero-visual"><div className="ga-visual-ring"/><div className="ga-visual-core"><span>META</span><strong>ADS</strong><small>AUDIENCE → OFFER → DEMAND</small></div><span className="ga-orbit ga-orbit-1">AUDIENCE</span><span className="ga-orbit ga-orbit-2">CREATIVE</span><span className="ga-orbit ga-orbit-3">LEAD QUALITY</span></div>
      </div>
    </div></section>

    <section className="ga-section"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">The problem</p><h2>Meta can generate attention quickly. That does not mean it generates useful demand.</h2></div><div className="ga-pain-grid">{[['01','“We are getting leads, but they are not serious.”','Low cost lead volume can hide weak audience signals, vague offers, weak creative promises or insufficient qualification.'],['02','“Our ads worked before, but performance has dropped.”','Creative fatigue, audience saturation and changing response can reduce performance when testing is not built into the system.'],['03','“We do not know which creative is actually working.”','Without clear hypotheses and meaningful conversion signals, creative optimisation becomes subjective instead of evidence based.'],['04','“Meta shows conversions, but sales sees little value.”','The platform can optimise toward the wrong action when the conversion signal does not represent the quality of opportunity your business needs.']].map(([n,title,text]) => <article className="ga-pain" key={n}><span>{n}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="ga-section-note">The answer is not simply boosting more posts or increasing spend. Meta needs a clear audience, a compelling offer, strong creative and a feedback loop that tells you which enquiries are actually worth pursuing.</p></div></section>

    <section className="ga-section ga-included"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">Strategic insight</p><h2>Meta Ads create demand by connecting four decisions.</h2><p><strong>Who should see it?</strong> Audience. <strong>Why should they care?</strong> Offer. <strong>Why should they stop?</strong> Creative. <strong>Why should they enquire?</strong> Conversion path and qualification.</p></div><div className="ga-outcome"><span>The job</span><strong>Put the right offer in front of the right audience and turn attention into enquiries your business can actually use.</strong></div></div></section>

    <section className="ga-section"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">What's included</p><h2>Meta Ads management built around the whole demand creation system.</h2><p>The work covers the decisions before the click, the experience after the click and the quality of what reaches sales.</p></div><div className="ga-included-grid">{included.map(([title,text]) => <div className="ga-included-item" key={title}><span>✓</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>

    <section className="ga-section ga-included"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">The process</p><h2>From audience hypothesis to better demand.</h2></div><div className="ga-process">{[['01','Audit','I review the account, existing campaigns, audiences, creative, offers, forms, landing pages, tracking and lead quality before changing the setup.'],['02','Define the demand','I clarify the audience, offer, buying trigger and qualification criteria the campaign needs to attract.'],['03','Build the system','I structure prospecting, retargeting and lead generation around the commercial goal, with creative angles and conversion paths aligned to each stage.'],['04','Test and optimise','I compare audience, offer and creative combinations, review performance signals and move budget toward stronger evidence.'],['05','Connect marketing to sales','Where CRM data is available, I use downstream lead quality to understand which campaigns are producing better opportunities, not simply more forms.']].map(([n,title,text]) => <article className="ga-process-item" key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

    <section className="ga-proof"><div className="container"><div className="ga-proof-grid"><div><p className="services-eyebrow">Relevant experience</p><h2>Paid social for businesses where the quality of demand matters.</h2><p>I have worked across immigration and visa services, attestation and professional services, healthcare and wellness, recruitment and HR, business services and other high consideration offers.</p></div><div className="ga-proof-card"><span>Experience across</span><strong>Immigration · Attestation · Healthcare · Recruitment · B2B</strong><p>Once verified campaign and CRM figures are available, this section can show specific spend, qualified lead cost, lead to opportunity rate and conversion metrics. I will not publish unsupported numbers.</p></div></div></div></section>

    <section className="ga-section"><div className="container ga-diff"><div><p className="services-eyebrow">Why Ashwin</p><h2>You work directly with the person making the campaign decisions.</h2></div><div><p>I do not treat Meta Ads as an isolated platform task. I look at <strong>Audience → Offer → Creative → Landing Page → Lead Form → CRM → Lead Quality</strong> as one acquisition system.</p><p>That means the question is not simply “Which ad has the cheapest lead?” It is “Which combination is producing the type of demand the business actually wants?”</p></div></div></section>

    <section className="ga-section ga-faq"><div className="container"><div className="ga-section-heading"><p className="services-eyebrow">FAQ</p><h2>Questions business owners ask before handing over Meta Ads budget.</h2></div><div className="ga-faq-list">{faq.map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></div></section>

    <section className="ga-section ga-social"><div className="container"><p className="services-eyebrow">Keep demand creation connected</p><h2>Meta Ads work better when the rest of the journey is measured.</h2><div className="ga-related-grid"><Link to="/services/landing-page-optimisation"><span>01</span><strong>Landing Page Optimisation</strong><small>Turn attention into action →</small></Link><Link to="/services/lead-generation"><span>02</span><strong>Lead Generation</strong><small>Turn enquiries into a healthier pipeline →</small></Link><Link to="/services/hubspot"><span>03</span><strong>HubSpot CRM & Automation</strong><small>Understand what happens after the lead →</small></Link></div></div></section>

    <section className="ga-final"><div className="container"><p className="services-eyebrow">Not sure whether your Meta Ads are attracting the right audience?</p><h2>Let's spend 15 minutes looking at it.</h2><p>I will review the biggest potential issues in your current setup and explain what I would prioritise.</p><a className="ga-primary" href={whatsappUrl} target="_blank" rel="noreferrer">Book a Free 15 Minute Meta Ads Audit <span>↗</span></a><small>No long presentation. No obligation. Just a practical review.</small></div></section>
  </main>
}
