import portrait from '../../../assets/ashwin-james-portrait.png'
import signature from '../../../assets/ashwin-signature.png'
import './AvailabilityIndicator.css'

const linkedinUrl = 'https://www.linkedin.com/in/ashwin-james'

export default function AboutPreview() {
  return <section id="about" className="home-section about-preview"><div className="container about-preview-grid"><div className="portrait-frame reveal-home"><div className="portrait-glow" /><div className="portrait-inner"><img className="portrait-image" src={portrait} alt="Professional portrait of Ashwin James, Performance Marketing Specialist in UAE" loading="lazy" /><div className="portrait-overlay" /><span className="availability"><span className="availability-dot" aria-hidden="true" />Available to work</span><div className="portrait-info"><div className="portrait-quote">“Build the system, not just the campaign.”</div><div className="portrait-divider" /><div className="portrait-bottom"><div className="portrait-caption"><strong>Ashwin James</strong><span>Performance Marketing &amp; Growth Systems Specialist</span></div><a className="linkedin-button" href={linkedinUrl} target="_blank" rel="noopener noreferrer" aria-label="View Ashwin James on LinkedIn"><span>in</span></a></div></div></div></div><div className="about-preview-copy reveal-home"><p className="home-eyebrow">A practical growth partner</p><h2>A disciplined way to turn marketing spend into commercial momentum.</h2><div className="about-copy"><p>Good growth work starts by understanding the business behind the brief: your market, the buying decision, your sales reality, and where revenue is currently leaking.</p><p>I bring the strategic view and hands on execution together. The aim is straightforward: fewer assumptions, better conversations with potential customers, and a marketing engine your business can confidently invest in.</p></div><div className="about-actions"><a className="text-link" href="/about">Work with Ashwin <span>→</span></a><img src={signature} alt="Ashwin signature" loading="lazy" /></div></div></div></section>
}
